{{ if eq .Values.fixicc_agent.storage.class "store-aws-ebs-fixicc" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: store-aws-ebs-fixicc
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
parameters:
  type: gp2
  encrypted: 'true'
reclaimPolicy: Delete
{{ end }}