---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fixicc-agent-configs-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.global.storage.accessModes }}
  storageClassName: {{ .Values.global.storage.class }}
  resources:
    requests:
      storage: {{ .Values.global.storage.fixicc_agent_configs.size }}
