---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fixicc-agent-configs-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.fixicc_agent.storage.accessModes }}
  {{- if .Values.fixicc_agent.storage.class }}
  storageClassName: {{ .Values.fixicc_agent.storage.class }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.fixicc_agent.storage.fixicc_agent_configs.size }}
