---

apiVersion: v1
kind: Service
metadata:
  name: fixedge
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: fixedge
  ports:
    - protocol: TCP
      port: {{ .Values.fixedge.port }}
      targetPort: {{ .Values.fixedge.port }}
