{{ if eq .Values.fixedge.storage.class "store-aws-ebs-fe" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: store-aws-ebs-fe
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
parameters:
  type: gp2
  encrypted: 'true'
reclaimPolicy: Delete
{{ end }}
