{{ if eq .Values.fixedge.storage.class "storage-fe" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-fe
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
parameters:
  type: gp2
  encrypted: 'true'
reclaimPolicy: Delete
{{ end }}
