---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fixedge-configs-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.storage.accessModes }}
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.fe_configs.size }}


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fixedge-session-logs-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.storage.accessModes }}
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.fe_sessions_logs.size }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fixedge-app-logs-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.storage.accessModes }}
  storageClassName: {{ .Values.storage.class }}
  resources:
    requests:
      storage: {{ .Values.storage.fe_app_logs.size }}
