fixicc_agent:
  image:
    url: 611262376458.dkr.ecr.eu-central-1.amazonaws.com/fixicc-agent
    version: 6.13.1-518
    imagePullPolicy: Always
  port: 8005
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 20
  NLB:
    enabled: true
    allowCIDR:
      - 86.57.255.88/29
      - 174.128.60.0/24
  resources:
    requests:
      cpu: 0.2
      memory: 200Mi
    limits:
      cpu: 0.2
      memory: 200Mi
  storage:
    class: storage-fixicc-agent
    accessModes: ReadWriteOnce
    fixicc_agent_configs:
      size: 1Gi