fixicc_agent:
  image:
    url: morozandralek/fixicc-agent
    version: latest
    imagePullPolicy: Always
  port: 8005
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 20
  NLB:
    enabled: false
    allowCIDR: []
  resources:
    requests:
      cpu: 0.2
      memory: 200Mi
    limits:
      cpu: 0.2
      memory: 200Mi
  storage:
    class: storage-fixicc-agent
    accessModes: ReadWriteOnce
    fixicc_agent_configs:
      size: 1Gi