{{ if eq .Values.global.storage.class "syfe-default" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: syfe-default
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
parameters:
  type: gp2
  encrypted: 'true'
reclaimPolicy: Delete
{{ end }}
