storage:
  class: storage-fe
  accessModes: ReadWriteOnce
  fe_configs:
    size: 1Gi
  fe_sessions_logs:
    size: 10Gi
  fe_app_logs:
    size: 10Gi

force_init_configs: false
git_configs:
  url: https://github.com/morozandralek/helmcharts.git
  branch: main

imagePullSecrets: []

fixedge:
  image:
    url: 611262376458.dkr.ecr.eu-central-1.amazonaws.com/fixedge
    version: 6.13.1-518
    imagePullPolicy: Always
  port: 8901
  httpAdmPort: 8903
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 20
  resources:
    requests:
      cpu: 0.5
      memory: 500Mi
    limits:
      cpu: 0.5
      memory: 500Mi
