---

apiVersion: v1
kind: Service
metadata:
  name: fixedge-java
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: fixedge-java
  ports:
    - name: fix
      protocol: TCP
      port: {{ .Values.global.fixedge_java.port }}
      targetPort: {{ .Values.global.fixedge_java.port }}
    - name: rest
      protocol: TCP
      port: {{ .Values.global.fixedge_java.httpAdmPort }}
      targetPort: {{ .Values.global.fixedge_java.httpAdmPort }}
    - name: fixeye
      protocol: TCP
      port: {{ .Values.global.fixeye_agent.port }}
      targetPort: {{ .Values.global.fixeye_agent.port }}

{{ if .Values.global.fixedge_java.loadbalancer.enable }}
