---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fixedge-java-session-logs-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.global.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.global.storage.fe_java_session_logs.size }}
